FROM ufoym/deepo:all-jupyter-py36-cu100

EXPOSE 8888

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
ENV UNAME beanzsoft
RUN useradd ${UNAME}
RUN mkdir -p /home/${UNAME}
RUN chown ${UNAME} /home/${UNAME}
# USER ${UNAME}

RUN apt-get update && apt-get -y install net-tools openssh-server
RUN sed -i "s|#Port 22|Port 7001 |g" /etc/ssh/sshd_config
RUN sed -i "s|#PermitRootLogin prohibit-password|PermitRootLogin yes |g" /etc/ssh/sshd_config

WORKDIR /home/${UNAME}
ENV PATH /home/${UNAME}/anaconda/bin:${PATH}
# don't change anaconda version 
RUN curl -o anaconda.sh https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh
RUN chmod +x anaconda.sh && \
./anaconda.sh -b -p /home/${UNAME}/anaconda
RUN conda update -n base -c defaults conda
RUN conda update --all
RUN ./anaconda/bin/conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing ipython
RUN ./anaconda/bin/conda install opencv 
RUN ./anaconda/bin/conda clean -ya
RUN export TORCH_CUDA_ARCH_LIST=8.6 # RTX 3090, A6000
# USER root

RUN source ./anaconda/etc/profile.d/conda.sh
# full-stack-deep-learning
RUN mkdir -p /home/${UNAME}/fsdl
WORKDIR /home/${UNAME}/fsdl
#RUN git clone https://github.com/junteken/fsdl-text-recognizer-2021-labs.git
COPY ./fsdl-text-recognizer-2021-labs /home/${UNAME}/fsdl/fsdl-text-recognizer-2021-labs
WORKDIR /home/${UNAME}/fsdl/fsdl-text-recognizer-2021-labs
RUN conda env update --prune -f environment.yml && \
source /home/${UNAME}/anaconda/etc/profile.d/conda.sh && \
source activate fsdl-text-recognizer-2021 && \
conda install pip && \
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html && \
# conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch && \ <--same result(no kernel image)
# conda install cudatoolkit=11.0 && \
pip install pip-tools && \
pip-compile ./requirements/prod.in && \
pip-compile ./requirements/dev.in && \
pip-sync ./requirements/prod.txt ./requirements/dev.txt && \
pip install ipykernel && \
python -m ipykernel install --user --name fsdl2021 --display-name "fsdl2021" 

#make fastai kernel spec
RUN conda create -n fastai python=3.7 && \
source /home/${UNAME}/anaconda/etc/profile.d/conda.sh && \
source activate fastai && \
conda install pip && \
conda install -c fastchan fastai && \
pip install ipykernel && \
python -m ipykernel install --user --name fastai --display-name "fastai" 

RUN jupyter notebook --generate-config
#RUN jupyter serverextension enable --py jupyterlab --sys-prefix
#RUN pip install plotly && \
#    conda install -c conda-forge nodejs && \
#    jupyter labextension install @jupyterlab/plotly-extension
#


#execute jupyter notebook
CMD ["jupyter", "notebook", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=", "--notebook-dir='/home'"]
